### PR TITLE
add new portfolio trackers to account page

### PR DESCRIPTION
**Pull request by Shungy**

### CODE REVIEW

**Comment by Shungy** [comment]
doesn't look ok with small screen

**Comment by SarjuHansaliya** [comment]
@Shungy in desktop view its looking good. may be in mobile view we can move "Track your portfolio on" row below "View on the C-Chain Explorer" ?

**Review by SarjuHansaliya — CHANGES_REQUESTED** [review]
@Shungy in desktop its looking good. for mobile may be we can move "Track your portfolio on" row below "View on the C-Chain Explorer" ?

**Comment by Shungy** [comment]
> @Shungy in desktop its looking good. for mobile may be we can move "Track your portfolio on" row below "View on the C-Chain Explorer" ?

Fixed! Also added custom css rules for the buttons.

**Review by SarjuHansaliya — APPROVED** [review]

**Pull request merged**
