### PR TITLE
[ENG-56] Export transactions to CSV

### PR DESCRIPTION
**Pull request by tonytamps**
[ENG-56](https://linear.app/pangolin/issue/ENG-56/export-transactions-to-csv)

To export transactions we need to take the transactions from the GQL API and shape them to something that can be converted to CSV.

The shaping of transactions could take a short while, depending on how many we're exporting. Doing it on load seemed completely unnecessary and I wanted to prove some user feedback while it was happening.

I've created a 3-state button that, when clicked, shows a loader while triggering the transaction shaping then changes to show a green download icon once they're ready.

You can find the button on the the account page in the transactions panel.

### CODE REVIEW

**Comment by HariSeldon23** [comment]
@SarjuHansaliya can you review this when you get a chance? Would like to get our testers involved to see what they think?

**Comment by HariSeldon23** [comment]
@tonytamps just noticed this is to merge to master. Can you adjust this to merge to `dev` branch. 

That way when it merges to `dev` we can get the testers involved on our beta site

**Comment by tonytamps** [comment]
Done. Apologies, I should have caught this.
Might be worth setting `dev` as the default branch if we always merge to it?

**Comment by HariSeldon23** [comment]
Good suggestion. I've changed default branch to dev. Will also change `Interface` repo

**Comment by bmino** [comment]
Looks cool!

Bugs I'm experiencing:

1) If I navigate to account A's page and download the csv info, change the url to another account (account B), and then try to download that account's csv info, I get account A's info still unless I refresh. Possibly a browser caching thing? Wanna make sure we are using the currently loaded url for this download.

2) When clicking the download button for an account that has 0 transactions, the app crashes

**Comment by tonytamps** [comment]
Thanks @bmino for the test, very much appreciated.
I've addressed both issues and improved the prop types.

I admit my testing wasn't as thorough as it should have been, that npm token problem blocked me a bit but I should have worked around it.

**Comment by bmino** [comment]
Good stuff! It's working well. Last suggestion I've got. What do you think about removing the 3 stage aspect of the button? Super smart not downloading this on load, but seems clunky to click the button multiple times. Especially for users with short lists of tx's the load is almost instant where you see a flicker on the button and wonder what happened. Thoughts on:

1) Starting the tx loading when user clicks the download button
2) Button changes to loading icon while pulling data
3) Download happens immediately when available
4) Button changes back to download icon

This avoids any potential flickering and avoids a user having to click the button twice

**Comment by tonytamps** [comment]
I've got no problems with that, I personally hate the 3 stage button too. 
I was trying to avoid making any calls on this until a designer could get involved and think about what they actually want.

There is one technical limitation, but I might be able to work around it.
I need to create the `transactionsBlob` url and then I use the click event on the 3rd button state to navigate there, which triggers the download.
I believe the browser will block me if I programatically try to click the element but I might be able to `fetch` the URL to work around the click security.

Regardless, I'm sure I can figure something out.

**Comment by tonytamps** [comment]
Okay, so I've done that and it feels pretty good. 
In Chrome it's quite seamless but in Firefox there is one minor problem that doesn't have a workaround.

image

The "from" is set to "blob:". There is an [old Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1053327) that doesn't seem like they'll fix anytime soon. I assume FF users will have seen this before so it shouldn't be too jarring.

**Comment by bmino** [comment]
Excellent! Push the changes and I'll review em :)

**Comment by tonytamps** [comment]
Already done, pushed before I commented - https://github.com/pangolindex/analytics/pull/70/commits/1c304b0a714a28072f2ed1f1c9809f221f1ff792

**Review by bmino — APPROVED** [review]

**Comment by bmino** [comment]
Great!

**Pull request merged**
